services:
  web:
    build: .
    container_name: bareprox
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/bareprox/config:/config  # config
      - /var/bareprox/data:/data    # db

        # sudo mkdir -p /var/bareprox/config
        # sudo mkdir -p /var/bareprox/data
        # sudo chown -R $(whoami):$(whoami) /var/bareprox