version: "3.8"


services:
  web:
    build: .
    container_name: bareprox-web
    restart: unless-stopped
    ports:
      - "8080:80"          # host:container
    volumes:
      - ./config:/config   # persists appsettings.json & DatabaseConfig.json
      - ./data:/data  
