version: "3.8"


services:
  web:
    build: .
    container_name: bareprox-web
    restart: unless-stopped
    ports:
      - "80:80"          # host:container
      - "443:443"
    volumes:
      - ./config:/config   # persists appsettings.json & DatabaseConfig.json
      - ./data:/data
