// <auto-generated />
using System;
using BareProx.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BareProx.Data.Migrations.QueryDb
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20251111104533_AddsnapTable")]
    partial class AddsnapTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BareProx.Models.InventoryClusterStatus", b =>
                {
                    b.Property<int>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClusterName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasQuorum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineHostCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalHostCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClusterId");

                    b.ToTable("InventoryClusterStatuses");
                });

            modelBuilder.Entity("BareProx.Models.InventoryHostStatus", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatusMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "HostId");

                    b.HasIndex("ClusterId");

                    b.ToTable("InventoryHostStatuses");
                });

            modelBuilder.Entity("BareProx.Models.InventoryMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("InventoryMetadata");
                });

            modelBuilder.Entity("BareProx.Models.InventoryNetappVolume", b =>
                {
                    b.Property<string>("VolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JunctionPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetappControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NfsIps")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SnapshotLockingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SvmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VolumeUuid");

                    b.HasIndex("JunctionPath");

                    b.HasIndex("NetappControllerId");

                    b.ToTable("InventoryNetappVolumes");
                });

            modelBuilder.Entity("BareProx.Models.InventoryStorage", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentFlags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Export")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImageCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchQuality")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetappVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "StorageId");

                    b.HasIndex("NetappVolumeUuid");

                    b.ToTable("InventoryStorages");
                });

            modelBuilder.Entity("BareProx.Models.InventoryVm", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "VmId");

                    b.HasIndex("ClusterId", "NodeName");

                    b.ToTable("InventoryVms");
                });

            modelBuilder.Entity("BareProx.Models.InventoryVmDisk", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBootDisk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClusterId", "VmId", "StorageId", "VolId");

                    b.HasIndex("ClusterId", "StorageId");

                    b.HasIndex("ClusterId", "VmId");

                    b.ToTable("InventoryVmDisks");
                });

            modelBuilder.Entity("BareProx.Models.InventoryVolumeReplication", b =>
                {
                    b.Property<string>("PrimaryVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.HasKey("PrimaryVolumeUuid", "SecondaryVolumeUuid");

                    b.HasIndex("SecondaryVolumeUuid");

                    b.ToTable("InventoryVolumeReplications");
                });

            modelBuilder.Entity("BareProx.Models.NetappSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExistsOnPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExistsOnSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReplicated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryVolume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecondaryControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapmirrorLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryControllerId");

                    b.HasIndex("SecondaryControllerId");

                    b.HasIndex("JobId", "SnapshotName")
                        .IsUnique();

                    b.ToTable("NetappSnapshots");
                });

            modelBuilder.Entity("BareProx.Models.InventoryVmDisk", b =>
                {
                    b.HasOne("BareProx.Models.InventoryStorage", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BareProx.Models.InventoryVm", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BareProx.Models.InventoryVolumeReplication", b =>
                {
                    b.HasOne("BareProx.Models.InventoryNetappVolume", null)
                        .WithMany()
                        .HasForeignKey("PrimaryVolumeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BareProx.Models.InventoryNetappVolume", null)
                        .WithMany()
                        .HasForeignKey("SecondaryVolumeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
