// <auto-generated />
using System;
using BareProx.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BareProx.Data.Migrations.QueryDb
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20251109123947_InitQueryInventory")]
    partial class InitQueryInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BareProx.Data.InventoryMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("InventoryMetadata");
                });

            modelBuilder.Entity("BareProx.Data.InventoryNetappVolume", b =>
                {
                    b.Property<string>("VolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JunctionPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetappControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NfsIps")
                        .HasColumnType("TEXT");

                    b.Property<string>("SvmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VolumeUuid");

                    b.HasIndex("JunctionPath");

                    b.HasIndex("NetappControllerId");

                    b.ToTable("InventoryNetappVolumes");
                });

            modelBuilder.Entity("BareProx.Data.InventoryStorage", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentFlags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Export")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImageCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchQuality")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetappVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "StorageId");

                    b.HasIndex("NetappVolumeUuid");

                    b.ToTable("InventoryStorages");
                });

            modelBuilder.Entity("BareProx.Data.InventoryVm", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "VmId");

                    b.HasIndex("ClusterId", "NodeName");

                    b.ToTable("InventoryVms");
                });

            modelBuilder.Entity("BareProx.Data.InventoryVmDisk", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBootDisk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClusterId", "VmId", "StorageId", "VolId");

                    b.HasIndex("ClusterId", "StorageId");

                    b.HasIndex("ClusterId", "VmId");

                    b.ToTable("InventoryVmDisks");
                });

            modelBuilder.Entity("BareProx.Data.InventoryVolumeReplication", b =>
                {
                    b.Property<string>("PrimaryVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryVolumeUuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.HasKey("PrimaryVolumeUuid", "SecondaryVolumeUuid");

                    b.HasIndex("SecondaryVolumeUuid");

                    b.ToTable("InventoryVolumeReplications");
                });

            modelBuilder.Entity("BareProx.Data.InventoryVmDisk", b =>
                {
                    b.HasOne("BareProx.Data.InventoryStorage", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BareProx.Data.InventoryVm", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BareProx.Data.InventoryVolumeReplication", b =>
                {
                    b.HasOne("BareProx.Data.InventoryNetappVolume", null)
                        .WithMany()
                        .HasForeignKey("PrimaryVolumeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BareProx.Data.InventoryNetappVolume", null)
                        .WithMany()
                        .HasForeignKey("SecondaryVolumeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
