// <auto-generated />
using BareProx.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BareProx.Data.Migrations.QueryDb
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20251107165317_InitQueryDb")]
    partial class InitQueryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");
#pragma warning restore 612, 618
        }
    }
}
